### ISSUE TITLE
mac编译失败

### ISSUE THREAD

**Issue by Xzhiming** [skynetlua/meiru-skynet#1]
lualib-src/ltls.c:5:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [luaclib/ltls.so] Error 1
make: *** [macosx] Error 2

**Comment by skynetlua** [comment]
首先谢谢你支持。由于https需要openssl模块，macox也需要这个模块。

**Comment by skynetlua** [comment]
> lualib-src/ltls.c:5:10: fatal error: 'openssl/err.h' file not found
> #include <openssl/err.h>
> ^~~~~~~~~~~~~~~
> 1 error generated.
> make[1]: *** [luaclib/ltls.so] Error 1
> make: *** [macosx] Error 2

由于我的mac电脑的openssl安装的比较早，忘记怎么安装的。搜索可以解决，如果你解决了，可不可以发给我链接呢？没有设备可以试，所以，就没法尝试

**Comment by Xzhiming** [comment]
感谢大佬的回答，
配置openssl环境变量解决了   
export CPATH=/usr/local/opt/openssl/include
export LIBRARY_PATH=/usr/local/opt/openssl/lib

**Comment by skynetlua** [comment]
现在shell编译脚本已进行了添加。
